<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-21 16:02
=======
# Generated by Django 4.0.3 on 2022-03-21 16:22
>>>>>>> ade889f3814389121a1cb8de55d9036d73d66240

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('techno', 'Techno'), ('hiphop', 'Hip-hop'), ('jazz', 'Jazz'), ('rap', 'Rap'), ('country', 'Country'), ('metal', 'Metal'), ('alternative', 'Alternative'), ('indie', 'Indie')], default='Pop', max_length=100)),
                ('audio', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('image', models.CharField(blank=True, default='https://i.imgur.com/D3aOVsJ.png', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='1.29', max_digits=6)),
            ],
        ),
    ]
