<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-21 16:35
=======
# Generated by Django 4.0.3 on 2022-03-21 19:02
>>>>>>> ade889f3814389121a1cb8de55d9036d73d66240

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
